main: me.jupdyke01.customenchantsredone.Main
name: CustomEnchantsRedone
api-version: 1.13
version: 1.0
author: jupdye01

commands:
  ce:
    description: Main command for CustomEnchantsRedone
    usage: /ce